openapi: 3.0.0
info:
  title: EazyShop Products APIs Definition
  version: 1.0.1
  description: A pet store manager
  termsOfService: htps://example.com/terms
  contact:
    email: suppot@example.com
    name: API Support
    url: https://www.example.com/support
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://development.gigantic-server.com/v1
    description: Development Server
  - url: https://staging.gigantic-server.com/v1
    description: Staging Server
  - url: https://api.gigantic-server.com/v1
    description: Production Server
  - url: https://{username}.server.com:{port}/{version}
    variables:
      username:
        default: demo
      port:
        enum:
          - "8443"
          - "443"
        default: "8443"
      version:
        default: v1
paths: {}
